tweett/Models/Posts.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweett.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts()
        {
            this.Retweets = new HashSet<Retweet>();
            this.Hashtags = new HashSet<Hashtag>();
            this.Reply = new HashSet<Reply>();
        }
    
        public int IdPost { get; set; }
        public string textP { get; set; }
        public string date_timeP { get; set; }
        public string AccountIdUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retweet> Retweets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hashtag> Hashtags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reply> Reply { get; set; }
    }
}

tweett/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tweett.Models;

namespace tweett.Controllers
{
    public class PostsController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Posts
        public ActionResult Index()
        {
            
            ViewData["Hashtags"] = db.HashtagSet.ToList();
            ViewData["posts"] = db.PostsSet.ToList();
            ViewData["account"] = db.AccountSet.ToList();
            ViewData["comment"] = db.ReplySet.ToList();
            if (Session["Username"] != null) {
                String user = Session["Username"].ToString();
                ViewData["User"] = db.AccountSet.FirstOrDefault(u => u.username == user);
            }
           
            return View();
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            ViewData["account"] = db.AccountSet.ToList();
            ViewData["Hashtags"] = db.HashtagSet.ToList();
            ViewData["account"] = db.AccountSet.ToList();
            ViewData["comment"] = db.ReplySet.ToList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           // dynamic mymodel = new ExpandoObject();
           // mymodel.Posts = db.PostsSet.Find(id);
           // mymodel.Reply = db.ReplySet.ToList();
           // mymodel.Hashtag = db.HashtagSet.ToList();
            Posts posts = db.PostsSet.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }
       


        // GET: Posts/Create
        public ActionResult Create()
        {
            return View();
        }

        

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "IdPost,textP,date_timeP,AccountIdUser")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                db.PostsSet.Add(posts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(posts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult comment([Bind(Include = "IdPost,textP,date_timeP,AccountIdUser")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                db.PostsSet.Add(posts);
                db.SaveChanges();
                return RedirectToAction("Details");
            }

            return View(posts);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.PostsSet.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPost,textP,date_timeP,AccountIdUser")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(posts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(posts);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.PostsSet.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            List<Reply> repliess = db.ReplySet.ToList();
            ViewData["repliess"] = repliess;
            return View(posts);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Posts posts = db.PostsSet.Find(id);
            db.PostsSet.Remove(posts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tweett/Controllers/RepliesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tweett.Models;

namespace tweett.Controllers
{
    public class RepliesController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: Replies
        public ActionResult Index()         
        {
            if (Session["Username"] != null)
            {
                String user = Session["Username"].ToString();
                ViewData["User"] = db.AccountSet.FirstOrDefault(u => u.username == user);
            }
          
            return View(db.ReplySet.ToList());
        }

        // GET: Replies/Details/5
        public ActionResult Details(int? id)

        {
            ViewData["Posts"] = db.PostsSet.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.ReplySet.Find(id);
            List<Posts> repliess = db.PostsSet.ToList();
            ViewData["repliess"] = repliess;
            if (reply == null)
            {
                return HttpNotFound();
            }
           
            return View(reply);
        }

        // GET: Replies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Replies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdReply,textR,date_time,PostIdPost,AccountIdUser")] Reply reply)
        {
            if (ModelState.IsValid)
            {
                db.ReplySet.Add(reply);
                db.SaveChanges();
                return RedirectToAction("Details","Posts", new { id = reply.IdReply });
            }

            return View(reply);
        }

        // GET: Replies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.ReplySet.Find(id);
            if (reply == null)
            {
                return HttpNotFound();
            }
            return View(reply);
        }

        // POST: Replies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdReply,textR,date_time,PostIdPost,AccountIdUser")] Reply reply)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reply).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Posts");
            }
            return View(reply);
        }

        // GET: Replies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.ReplySet.Find(id);
            if (reply == null)
            {
                return HttpNotFound();
            }
            return View(reply);
        }

        // POST: Replies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reply reply = db.ReplySet.Find(id);
            db.ReplySet.Remove(reply);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tweett/Views/Posts/Create.cshtml
@model tweett.Models.Posts

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Posts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.textP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.textP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.textP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_timeP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_timeP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_timeP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountIdUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountIdUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountIdUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>

    @Html.ActionLink("Back to List", "Index")
</div>

tweett/Views/Posts/Delete.cshtml
@model tweett.Models.Posts

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Posts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.textP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.textP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_timeP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_timeP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountIdUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountIdUser)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tweett/Views/Posts/Details.cshtml
@model tweett.Models.Posts
@{
    ViewBag.Title = "Details";
    var Haash = ViewData["Hashtags"] as List<tweett.Models.Hashtag>;
    var posts = ViewData["posts"] as List<tweett.Models.Posts>;
    var account = ViewData["account"] as List<tweett.Models.Account>;
    var reply = ViewData["comment"] as List<tweett.Models.Reply>;
}

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8 " style="margin-top:20px;">
        <br>
        
            <div class="tweet">
                    <div class="row">
                        <div class="col-lg-2"><div class="user3 img-circle" style="margin-left:20px;"> </div></div>
                        <div class="col-lg-10" style="margin-top:20px; padding-left:50px;">
                        @foreach(var a in account)
                        {
                           @Html.ActionLink(a.username, "Profile", "Accounts", new { id = a.IdUser }, null)
                            
                        }
                        @Html.DisplayFor(model => model.date_timeP)<br>
                         @Html.DisplayFor(model => model.textP)
                    
                        <br>
                       

                    @foreach (var Hash in Haash)
                    {
                        @Html.ActionLink(Hash.create_hashtag, "Details", "Hashtags", new { id = Hash.IdHash }, null)
                    }

                    <br>
                   
                    <br>
                    <br>
                            </div>
                        </div>
                 </div>
           
                   <div  style="margin-top:20px;">
                                           @foreach (var c in reply)
                                           {
                                            <div class="tweet">

                                                @Html.DisplayFor(model => c.textR)   
                                                @Html.DisplayFor(model => c.date_time)    <br>
                                            </div>
                                           }

                   </div>
                    @Html.ActionLink("Reply", "Create", "Replies")
     
            </div>
    <div class="col-lg-2"></div>
    </div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPost }) |
    @Html.ActionLink("Back to List", "Index")

</p>*@

tweett/Views/Posts/Edit.cshtml
@model tweett.Models.Posts

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Posts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPost)

        <div class="form-group">
            @Html.LabelFor(model => model.textP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.textP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.textP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_timeP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_timeP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_timeP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountIdUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountIdUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountIdUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tweett/Views/Posts/Index.cshtml
@model tweett.Models.Posts

@{

    ViewBag.Title = "Index";
    var Haash = ViewData["Hashtags"] as List<tweett.Models.Hashtag>;
    var posts = ViewData["posts"] as List<tweett.Models.Posts>;
    var account = ViewData["account"] as List<tweett.Models.Account>;
    var reply = ViewData["comment"] as List<tweett.Models.Reply>;
    var user = ViewData["User"] as tweett.Models.Account;
    var hash = ViewData["HasH"] as tweett.Models.Hashtag;
}


<div class="container">
    <div class="row">
        <div class="col-md-4">
           
            
            <div class="ProfileCard">
                <div class="img-circle user"></div>
                <div class="username">
                    @foreach (var acc in account)
                    {
                        @Html.DisplayFor(modelitem => acc.username)
                    }
                </div>
            </div>
        </div>
        <div class="col-md-8">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal addtweet" style="margin-bottom:10px;">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group" style="padding-top:10px;">
                        <div class="col-sm-12">
                            @Html.EditorFor(model => model.textP, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.textP, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.date_timeP, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.ToString("h:mm:ss"), @style = "display: none" } })
                            @Html.ValidationMessageFor(model => model.date_timeP, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AccountIdUser, new { htmlAttributes = new { @class = "form-control", @Value = user.IdUser, @style = "display: none" }  })
                            @Html.ValidationMessageFor(model => model.AccountIdUser, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <button value="Create" class="btn btn-default" type="submit" style="position:absolute; right:30px; top:0px; margin-top:10px;">Tweet</button>


                </div>
            }

            <table class="table">

                @foreach (var item in posts)
                {
                    <tr class="tweet">
                        <td>
                           @foreach (var acc in account)
                           {
                            @Html.DisplayFor(modelitem => acc.username)
                           }
                            @Html.DisplayFor(modelitem => item.date_timeP)
                           
                            <br>
                            @Html.DisplayFor(modelItem => item.textP)
                            @foreach (var Hash in Haash)
                            {
                                @Html.ActionLink(Hash.create_hashtag, "Details", "Hashtags", new { id = Hash.IdHash }, null)
                            }
                            <br>
                            @Html.ActionLink("Edit", "Edit", new { id = item.IdPost }) |
                            @Html.ActionLink("Details", "Details", new { id = item.IdPost }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.IdPost }) |
                            @Html.ActionLink("Create Hashtag", "Create", "Hashtags")
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>